trigger:
- master

pool:
  vmImage: 'ubuntu-latest' # Specifies the virtual machine image to use for the job
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    command: 'login'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      make image
      make push
    workingDirectory: '$(Build.SourcesDirectory)' # Use the directory where your repo is cloned
    
