name: Run Makefile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Makefile
      run: |


        # Run the default target or a specific target
        make image
        make push

