name: Run Makefile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Replace with your Docker username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Replace with your Docker password or token
        registry: ${{ secrets.DOCKER_REGISTRY }}
        

    - name: Run Makefile
      run: |
        # Run the default target or a specific target
        make image
        make push
